apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seamap
  namespace: seamap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: rook-cephfs

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seamap-local
  namespace: seamap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdal
  namespace: seamap
  labels:
    app: gdal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdal
  template:
    metadata:
      labels:
        app: gdal
    spec:
      containers:
        - name: gdal-container
          image: debian:bullseye-slim
          command: ["/bin/bash", "-c"]
          args:
            - |
              apt-get update && \
              apt-get install -y wget curl postgresql-client gdal-bin unzip screen pip git && \
              sleep infinity
          volumeMounts:
            - name: seamap
              mountPath: /data/seamap
            # - name: seamap-local
            #   mountPath: /data/seamap-local
      volumes:
        - name: seamap
          persistentVolumeClaim:
            claimName: seamap
        # - name: seamap-local
        #   persistentVolumeClaim:
        #     claimName: seamap-local
      nodeSelector:
        mtk.seamap: "true"


# https://github.com/acalcutt/rio-rgbify
# rio rgbify -e terrarium --min-z 5 --max-z 12 -j 8 --bounding-tile [17,11,5] --format webp ../filled.tif emod.mbtiles
