apiVersion: apps/v1
kind: Deployment
metadata:
  name: planetiler
  namespace: seamap
spec:
  selector:
    matchLabels:
      app: planetiler
  template:
    metadata:
      labels:
        app: planetiler
    spec:
      containers:
      - name: planetiler
        image: ghcr.io/onthegomap/planetiler:latest
        command: ["/bin/sh"]
        args: ["-c", "sleep infinity"]  # Bleibt laufen f√ºr manuelle Befehle
      nodeSelector:
        mtk.seamap_planetiler: "true"
